services:
  - type: web
    name: buddy-backend
    runtime: python
    rootDir: backend
    pythonVersion: 3.12
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./buddy.db
