services:
  - type: web
    name: buddy-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
startCommand: bash -lc 'cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./buddy.db
